/* Generated By:JavaCC: Do not edit this line. MozartConstants.java */
package mozart;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MozartConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int EQUAL = 9;
  /** RegularExpression Id. */
  int GREATER = 10;
  /** RegularExpression Id. */
  int GREATEREQUAL = 11;
  /** RegularExpression Id. */
  int CONSTANT = 12;
  /** RegularExpression Id. */
  int WORD = 13;
  /** RegularExpression Id. */
  int VAR = 14;
  /** RegularExpression Id. */
  int LOWER = 15;
  /** RegularExpression Id. */
  int UPPER = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\">\"",
    "\">=\"",
    "<CONSTANT>",
    "<WORD>",
    "<VAR>",
    "<LOWER>",
    "<UPPER>",
    "<DIGIT>",
    "\"nil\"",
    "\"[\"",
    "\"]\"",
    "\"local\"",
    "\"in\"",
    "\"end\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"proc\"",
    "\"{\"",
    "\"}\"",
  };

}
